general_server_app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'markets#index'

  resources :markets, only: %i[index show] do
    resources :stock_symbols,
              only: %i[index show], controller: 'markets/stock_symbols' do
      get :search, on: :collection
      resources :daily_stock_summaries, only: %i[index], shallow: true
    end
    resources :results, on: :member, only: [:index], controller: 'markets/results'
  end

  resources :tools, only: %i[index] do
    get :covariance, on: :collection
  end

  resources :stock_symbols, only: %i[index] do
    get :search, on: :collection
  end

  resource :users, only: %i[new create] do
    get :login, on: :collection
    get :profile, on: :collection
    get :favorited, on: :collection, as: :favorited_stocks
    get :confirm, on: :collection
    post :create_session, on: :collection
    delete :logout, on: :collection
  end

  namespace :api do
    namespace :v1 do
      resource :auth, only: %i[create]
      get 'user_favorite_symbols',
          to: 'user_favorite_symbols#index', as: :user_favorited_stocks
      resources :stock_symbols,
                only: %i[short_summary], constraints: { id: /.+/ } do
        get 'user_favorite_symbols/check',
            to: 'user_favorite_symbols#check', as: :user_favorite_symbols_check
        post 'user_favorite_symbols/toggle',
             to: 'user_favorite_symbols#toggle',
             as: :user_favorite_symbols_toggle
        resources :daily_stock_summaries, only: %i[index], shallow: true
        get :short_summary, on: :member
      end

      get :intraday_stock_market_data,
          controller: 'intraday_stock_market_data', action: 'show'
    end
  end

  namespace :panel do
    root to: 'panel#index'
    resources :articles
  end

  mount Peek::Railtie => '/peek' if Rails.env.development?

  require 'sidekiq/web'
  Sidekiq::Web.set :sessions, false
  mount Sidekiq::Web => '/sidekiq'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest('adminadmin')
    ) &
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(password),
        ::Digest::SHA256.hexdigest('passwordpassword')
      )
  end


  # mount PgHero::Engine, at: 'pghero' if Rails.env.production?
end

general_server_app/app/views/layouts/_breadcrumbs.html.slim
.container.mobilePadding
  nav.breadcrumb aria-label="breadcrumbs"
    == breadcrumbs pretext: "You are here: ",
      semantic: true,
      style: :ul,
      current_class: 'is-active'

general_server_app/app/views/layouts/_errors.html.slim
div
  - errors.each do |error|
    = error

general_server_app/app/views/layouts/_top_menu.html.slim
/ .has-shadow
nav#navbar.navbar.is-light [
  data-controller='header-menu'
  aria-label="main navigation"
  role="navigation"
]
  .container
    .navbar-brand
      = link_to 'Heroes of markets', root_path, class: 'navbar-item'

      a [
        role="button"
        class="navbar-burger burger"
        aria-label="menu"
        aria-expanded="false"
        data-target='header-menu.menuButton' ]
        span aria-hidden="true"
        span aria-hidden="true"
        span aria-hidden="true"

    .navbar-menu data-target='header-menu.menuContainer'
      .navbar-start
        = link_to 'Home', root_path, class: 'navbar-item'
        = link_to 'Stocks', stock_symbols_path, class: 'navbar-item'
        = link_to 'Tools', tools_path, class: 'navbar-item'
      .navbar-end
        - if @current_user.present?
          .navbar-item.has-dropdown.is-hoverable
            .navbar-link.button.is-light = @current_user.email
            .navbar-dropdown
              = link_to 'Profile', profile_users_path, class: 'navbar-item'
              = link_to 'Favorited stocks', favorited_stocks_users_path, class: 'navbar-item'
              hr.navbar-divider
              button.navbar-item  data-target='header-menu.logoutButton' Exit
        - else
          .navbar-item
            .buttons
              = link_to new_users_path, class: 'button is-primary'
                strong Sign up
              = link_to login_users_path, class: 'button is-light'
                strong Sign in

general_server_app/app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    - if Rails.env.production?
      = javascript_include_tag 'https://www.googletagmanager.com/gtag/js?id=UA-7091055-22', async: true
      = javascript_pack_tag 'google_analytics', defer: true
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application', defer: true
    = display_meta_tags heroes_of_markets_meta_tags
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="yandex-verification" content="afd9c21f42e86e1f"
  body
    = render 'layouts/top_menu'
    = render 'layouts/breadcrumbs'
    .container.mobilePadding
      = yield
    footer.footer
      .container
        = link_to 'admin@heroes-of-markets.com', 'mailto:admin@heroes-of-markets.com', title: 'Contacting email'