general_server_app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'markets#index'

  resources :markets, only: %i[index show] do
    resources :stock_symbols,
              only: %i[index show], controller: 'markets/stock_symbols' do
      get :search, on: :collection
      resources :daily_stock_summaries, only: %i[index], shallow: true
    end
    resources :results, on: :member, only: [:index], controller: 'markets/results'
  end

  resources :tools, only: %i[index] do
    get :covariance, on: :collection
  end

  resources :stock_symbols, only: %i[index] do
    get :search, on: :collection
  end

  resource :users, only: %i[new create] do
    get :login, on: :collection
    get :profile, on: :collection
    get :favorited, on: :collection, as: :favorited_stocks
    get :confirm, on: :collection
    post :create_session, on: :collection
    delete :logout, on: :collection
  end

  namespace :api do
    namespace :v1 do
      resource :auth, only: %i[create]
      get 'user_favorite_symbols',
          to: 'user_favorite_symbols#index', as: :user_favorited_stocks
      resources :stock_symbols,
                only: %i[short_summary], constraints: { id: /.+/ } do
        get 'user_favorite_symbols/check',
            to: 'user_favorite_symbols#check', as: :user_favorite_symbols_check
        post 'user_favorite_symbols/toggle',
             to: 'user_favorite_symbols#toggle',
             as: :user_favorite_symbols_toggle
        resources :daily_stock_summaries, only: %i[index], shallow: true
        get :short_summary, on: :member
      end

      get :intraday_stock_market_data,
          controller: 'intraday_stock_market_data', action: 'show'
    end
  end

  namespace :panel do
    root to: 'panel#index'
    resources :articles
  end

  mount Peek::Railtie => '/peek' if Rails.env.development?

  require 'sidekiq/web'
  Sidekiq::Web.set :sessions, false
  mount Sidekiq::Web => '/sidekiq'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest('adminadmin')
    ) &
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(password),
        ::Digest::SHA256.hexdigest('passwordpassword')
      )
  end


  # mount PgHero::Engine, at: 'pghero' if Rails.env.production?
end

general_server_app/app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  has_rich_text :content
  validates :title, :content, :source_description, :source_link, presence: true

  has_many :article_stock_symbol_effects
  has_many :stock_symbols, through: :article_stock_symbol_effects
  has_many :markets, through: :stock_symbols

  accepts_nested_attributes_for :article_stock_symbol_effects
end

general_server_app/app/controllers/panel/articles_controller.rb
# frozen_string_literal: true

class Panel::ArticlesController < PanelController
  include Pagy::Backend

  def index
    @pagy, @articles = pagy(Article)
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
    @article.article_stock_symbol_effects.build
  end

  def update
    @article = Article.find(params[:id])

    if @article.update prepared_article_params
      redirect_to panel_articles_path(@article)
    else
      render :edit
    end
  end

  def create
    @article = Article.new article_params

    if @article.save
      redirect_to edit_panel_article_path(@article)
    else
      render :new
    end
  end

  private

  def article_params
    params.require(:article).permit(
      :title, :content, :source_link, :source_description,
      article_stock_symbol_effects_attributes: %i[stock_symbol_id effect id]
    )
  end

  def prepared_article_params
    local_params = article_params.to_h

    local_params[:article_stock_symbol_effects_attributes] = local_params[:article_stock_symbol_effects_attributes].values.filter { |assea| assea['effect'].present? && assea['stock_symbol_id'].present? }

    local_params
  end
end

general_server_app/app/controllers/panel/panel_controller.rb
# frozen_string_literal: true

class Panel::PanelController < PanelController
  def index; end
end

general_server_app/app/controllers/panel_controller.rb
# frozen_string_literal: true

class PanelController < ApplicationController
  private

  def authorize_user
    raise NotAuthorizedException unless current_user
    raise NotAuthorizedException unless current_user.has_role? :panel_user
  end
end

general_server_app/app/views/panel/articles/_articleItem.html.slim
.itemsList__item
  = link_to article.title, edit_panel_article_path(article)

general_server_app/app/views/panel/articles/_form.html.slim
= form_with model: [:panel, @article] do |f|
  = render 'layouts/errors', errors: @article.errors.full_messages

  .field
    = f.label :title, class: 'label'
    = f.text_field :title, class: 'input'

  .field
    = f.label :content, class: 'label'
    = f.rich_text_area :content, class: 'textarea'

  .columns
    .column.field
      = f.label :source_link, class: 'label'
      = f.text_field :source_link, class: 'input'
    .column.field
      = f.label :source_description, class: 'label'
      = f.text_field :source_description, class: 'input'

  - if @article.persisted?
    h2.subtitle Effect on symbols
    .fieldset
      = f.fields_for :article_stock_symbol_effects do |assef, id|
        .columns
          .column
            = assef.label :stock_symbol, class: 'label'
            = assef.text_field :stock_symbol_id, class: 'input'
          .column
            = assef.label :effect, class: 'label'
            .select
              = assef.select :effect,
                ArticleStockSymbolEffect.states.collect { |state| [state[0], state[1]] },
                include_blank: true

  = f.button 'Create', class: 'button'

general_server_app/app/views/panel/articles/edit.html.slim
.level
  .level-left
    h1.title = @article.title
  .level-right
    = link_to 'Back', panel_articles_path, class: 'button is-primary'

= render 'panel/articles/form'

general_server_app/app/views/panel/articles/index.html.slim
.level
  .level-left
    h1.title Articles
  .level-right
    = link_to 'Create new', new_panel_article_path, class: 'button is-primary'

.itemsList
  = render partial: 'panel/articles/articleItem',
    collection: @articles,
    as: :article,
    cached: true

general_server_app/app/views/panel/articles/new.html.slim
.level
  .level-left
    h1.title Create new
  .level-right
    = link_to 'Back', panel_articles_path, class: 'button is-primary'

= render 'panel/articles/form'